<?php
/**
 * @file
 * core00_core.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function core00_core_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_address'
  $field_bases['field_address'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_address',
    'field_permissions' => array(
      'type' => 2,
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'locked' => 0,
    'module' => 'addressfield',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'addressfield',
  );

  // Exported field_base: 'field_body'
  $field_bases['field_body'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_body',
    'field_permissions' => array(
      'type' => 2,
    ),
    'foreign keys' => array(
      'format' => array(
        'columns' => array(
          'format' => 'format',
        ),
        'table' => 'filter_format',
      ),
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_custom_php'
  $field_bases['field_custom_php'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_custom_php',
    'field_permissions' => array(
      'type' => 2,
    ),
    'foreign keys' => array(
      'format' => array(
        'columns' => array(
          'format' => 'format',
        ),
        'table' => 'filter_format',
      ),
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_email'
  $field_bases['field_email'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_email',
    'field_permissions' => array(
      'type' => 2,
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'locked' => 0,
    'module' => 'email',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'email',
  );

  // Exported field_base: 'field_file_image_alt_text'
  $field_bases['field_file_image_alt_text'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_file_image_alt_text',
    'foreign keys' => array(
      'format' => array(
        'columns' => array(
          'format' => 'format',
        ),
        'table' => 'filter_format',
      ),
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_file_image_title_text'
  $field_bases['field_file_image_title_text'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_file_image_title_text',
    'foreign keys' => array(
      'format' => array(
        'columns' => array(
          'format' => 'format',
        ),
        'table' => 'filter_format',
      ),
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_network_link'
  $field_bases['field_network_link'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_network_link',
    'field_permissions' => array(
      'type' => 0,
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'locked' => 0,
    'module' => 'link',
    'settings' => array(
      'attributes' => array(
        'class' => '',
        'rel' => '',
        'target' => 'default',
      ),
      'display' => array(
        'url_cutoff' => 80,
      ),
      'enable_tokens' => 1,
      'title' => 'optional',
      'title_maxlength' => 128,
      'title_value' => '',
      'url' => 0,
    ),
    'translatable' => 0,
    'type' => 'link_field',
  );

  // Exported field_base: 'field_network_links'
  $field_bases['field_network_links'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_network_links',
    'field_permissions' => array(
      'type' => 2,
    ),
    'foreign keys' => array(),
    'indexes' => array(
      'revision_id' => array(
        0 => 'revision_id',
      ),
    ),
    'locked' => 0,
    'module' => 'field_collection',
    'settings' => array(
      'hide_blank_items' => 1,
      'hide_initial_items' => 1,
      'path' => '',
      'profile2_private' => 0,
    ),
    'translatable' => 0,
    'type' => 'field_collection',
  );

  // Exported field_base: 'field_network_name'
  $field_bases['field_network_name'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_network_name',
    'field_permissions' => array(
      'type' => 0,
    ),
    'foreign keys' => array(),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'Acrobat' => 'Acrobat',
        'Aim' => 'Aim',
        'Amazon' => 'Amazon',
        'Android' => 'Android',
        'Angellist' => 'Angellist',
        'Appnet' => 'Appnet',
        'Appstore' => 'Appstore',
        'Bitbucket' => 'Bitbucket',
        'Blogger' => 'Blogger',
        'Buffer' => 'Buffer',
        'Cloudapp' => 'Cloudapp',
        'Delicious' => 'Delicious',
        'Digg' => 'Digg',
        'Disqus' => 'Disqus',
        'Dribbble' => 'Dribbble',
        'Dropbox' => 'Dropbox',
        'Drupal' => 'Drupal',
        'Duckduckgo' => 'Duckduckgo',
        'Dwolla' => 'Dwolla',
        'Ebay' => 'Ebay',
        'Eventasaurus' => 'Eventasaurus',
        'Eventbrite' => 'Eventbrite',
        'Eventful' => 'Eventful',
        'Evernote' => 'Evernote',
        'Facebook' => 'Facebook',
        'Fivehundredpx' => 'Fivehundredpx',
        'Flattr' => 'Flattr',
        'Flickr' => 'Flickr',
        'Forrst' => 'Forrst',
        'Foursquare' => 'Foursquare',
        'Github' => 'Github',
        'Gmail' => 'Gmail',
        'Google' => 'Google',
        'Google Play' => 'Google Play',
        'Gowalla' => 'Gowalla',
        'Gplus' => 'Gplus',
        'Grooveshark' => 'Grooveshark',
        'Hackernews' => 'Hackernews',
        'Instagram' => 'Instagram',
        'Instapaper' => 'Instapaper',
        'Intensedebate' => 'Intensedebate',
        'itunes' => 'itunes',
        'Klout' => 'Klout',
        'Lanyrd' => 'Lanyrd',
        'Last FM' => 'Last FM',
        'Linkedin' => 'Linkedin',
        'Lkd.to' => 'Lkd.to',
        'Macstore' => 'Macstore',
        'Meetup' => 'Meetup',
        'Myspace' => 'Myspace',
        'Ninety Nine Designs' => 'Ninety Nine Designs',
        'OpenID' => 'OpenID',
        'Opentable' => 'Opentable',
        'Paypal' => 'Paypal',
        'Pinboard' => 'Pinboard',
        'Pinterest' => 'Pinterest',
        'Plancast' => 'Plancast',
        'Plurk' => 'Plurk',
        'Pocket' => 'Pocket',
        'Podcast' => 'Podcast',
        'Posterous' => 'Posterous',
        'Quora' => 'Quora',
        'Reddit' => 'Reddit',
        'RSS' => 'RSS',
        'Scribd' => 'Scribd',
        'Skype' => 'Skype',
        'Smashmag' => 'Smashmag',
        'Songkick' => 'Songkick',
        'Soundcloud' => 'Soundcloud',
        'Spotify' => 'Spotify',
        'Stackoverflow' => 'Stackoverflow',
        'Statusnet' => 'Statusnet',
        'Steam' => 'Steam',
        'Stripe' => 'Stripe',
        'Stumbleupon' => 'Stumbleupon',
        'Tumblr' => 'Tumblr',
        'Twitter' => 'Twitter',
        'Viadeo' => 'Viadeo',
        'Vimeo' => 'Vimeo',
        'VK' => 'VK',
        'Weibo' => 'Weibo',
        'Wikipedia' => 'Wikipedia',
        'Wordpress' => 'Wordpress',
        'Xing' => 'Xing',
        'Yahoo' => 'Yahoo',
        'Yelp' => 'Yelp',
        'Youtube' => 'Youtube',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_telephone'
  $field_bases['field_telephone'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_telephone',
    'field_permissions' => array(
      'type' => 2,
    ),
    'foreign keys' => array(
      'format' => array(
        'columns' => array(
          'format' => 'format',
        ),
        'table' => 'filter_format',
      ),
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
      'profile2_private' => 0,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_user_bio'
  $field_bases['field_user_bio'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_user_bio',
    'field_permissions' => array(
      'type' => 0,
    ),
    'foreign keys' => array(
      'format' => array(
        'columns' => array(
          'format' => 'format',
        ),
        'table' => 'filter_format',
      ),
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_user_picture'
  $field_bases['field_user_picture'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_user_picture',
    'foreign keys' => array(
      'fid' => array(
        'columns' => array(
          'fid' => 'fid',
        ),
        'table' => 'file_managed',
      ),
    ),
    'indexes' => array(
      'fid' => array(
        0 => 'fid',
      ),
    ),
    'locked' => 0,
    'module' => 'image',
    'settings' => array(
      'default_image' => 9,
      'uri_scheme' => 'public',
    ),
    'translatable' => 0,
    'type' => 'image',
  );

  // Exported field_base: 'title_field'
  $field_bases['title_field'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'title_field',
    'field_permissions' => array(
      'type' => 0,
    ),
    'foreign keys' => array(
      'format' => array(
        'columns' => array(
          'format' => 'format',
        ),
        'table' => 'filter_format',
      ),
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max_length' => 255,
      'profile2_private' => FALSE,
    ),
    'translatable' => 1,
    'type' => 'text',
  );

  return $field_bases;
}
