<?php
/**
 * @file
 * About the module here...
 */
function core00_module_form_alter(&$form, &$form_state, $form_id) {
/*  dsm($form_id); */
  if ($form_id == 'basic_contact_entityform_edit_form') {
    unset($form['field_full_name']['und'][0]['#title']);
/*     dsm($form); */
  }
}

/**
* Implements hook_field_default_fields_alter().
*
* Alter the default fields right before they are cached into the database.
*
* @param &$fields
*   By reference. The fields that have been declared by another feature.
*/

//Features API attempt to set default value of user image field
/*
function core00_module_field_default_fields_alter(&$fields) {
  dsm($fields);
  $source_dir = drupal_get_path('module', 'core00_module') . '/images';

  $field_default_images = array(
    'user-user-field_user_picture' => 'default_user.png',
    'field_user_picture' => 'default_user.png',    
  );

  foreach ($field_default_images as $field_name => $filename) {
    $source = $source_dir . '/' . $filename;
    $destination = 'default_images/' . $filename;
    if (isset($fields[$field_name])) {
      core00_module_set_default_image($fields[$field_name], $filename, $source, $destination);
    }
  }
}

function core00_module_set_default_image(&$field, $filename, $source, $destination) {
  // See if a default image hasn't been set for this field yet
  if (empty($field['field_config']['settings']['default_image'])) {
    // Dynamically set the user default image on the field
    $destination = file_default_scheme() . '://' . $destination;

    // Check to see if it exists already
    $result = db_select('file_managed', 'f')
      ->fields('f', array('fid'))
      ->condition('f.uri', $destination)
      ->execute();

    $fid = $result->fetchField();

    // Simulate an upload of the default user image
    if (!$fid && file_exists($source)) {
      $file = new stdClass;
      $file->filename = $filename;
      $file->timestamp = REQUEST_TIME;
      $file->uri = $source;
      $file->filemime = file_get_mimetype($source);
      $file->uid = 1;
      $file->status = 1;

      $file = file_copy($file, 'public://', FILE_EXISTS_REPLACE);

      $fid = $file->fid;
    }

    $field['field_config']['settings']['default_image'] = (string) $fid;
  }
}
*/