<?php

/**
* Implementation of hook_menu() to add menu item for map popup ajax request.
*/
function bulk_domain_check_menu() {
  $items = array();

  $items['admin/config/services/bds'] = array(
    'title' => 'Bulk Domain Check',
    'description' => 'perform bulk domain check',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bulk_domain_check_search_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'bulk_domain_check.admin.inc',
  );


  return $items;
}

/**
 * Implementation of hook_init().
 */
function bulk_domain_check_init() {
		$path = drupal_get_path('module', 'bulk_domain_check');
    drupal_add_js(array(
      'bulk_domain_check' => array(
        'path' => $path
      )
    ), 'setting');

}