name = Location
description = scubox location layout
preview = preview.png
template = location.layout

; Regions
regions[header]         																				= Header
regions[navigation]     																				= Navigation bar
regions[highlighted]    																				= Highlighted
regions[help]           																				= Help
regions[content]        																				= Content
regions[sidebar_first]  																				= First sidebar
regions[sidebar_second] 																				= Second sidebar
regions[footer]         																				= Footer

regions[hero]                                                   = Hero
regions[nav_bottom]                                             = Nav Bottom
regions[map_first]      																				= Map First
regions[map_second]     																				= Map Second
regions[map]            																				= Map
regions[content_list]            																= Content List
regions[title_bar]      																				= Title Bar



; Stylesheets
stylesheets[all][] 																							= assets/css/styles/layouts/location.layout.css