<?php

/**
 * Implementation of hook_feeds_plugins(). 
 * Registers extended version of FeedsTermProcessor.inc to include additional tagets.
 */
function core44_feeds_pimp_feeds_plugins() {
  $info = array();
  if (module_exists('taxonomy')) {
      $info['FeedsTermProcessorExtended'] = array(
        'name' => 'Taxonomy term processor extended',
        'description' => 'Extended version of the taxonomy term processor.',
        'help' => 'Create taxonomy terms from parsed content. ',
        'handler' => array(
          'parent' => 'FeedsProcessor',
          'class' => 'FeedsTermProcessorExtended',
          'file' => 'FeedsTermProcessorExtended.inc',
          'path' => drupal_get_path('module', 'core44_feeds_pimp') . '/includes',
        ),
      );
      $info['FeedsVocabProcessor'] = array(
        'name' => 'Vocabulary processor',
        'description' => 'Vocabulary processor.',
        'help' => 'Create vocabularies from parsed content. ',
        'handler' => array(
          'parent' => 'FeedsProcessor',
          'class' => 'FeedsVocabProcessor',
          'file' => 'FeedsVocabProcessor.inc',
          'path' => drupal_get_path('module', 'core44_feeds_pimp') . '/includes',
        ),
      );  
    }
    
    $info['FeedsNodeProcessorExtended'] = array(
      'name' => 'Node processor extended',
      'description' => 'Extended version of the node processor.',
      'help' => 'Create nodes from parsed content. ',
      'handler' => array(
        'parent' => 'FeedsProcessor',
        'class' => 'FeedsNodeProcessorExtended',
        'file' => 'FeedsNodeProcessorExtended.inc',
        'path' => drupal_get_path('module', 'core44_feeds_pimp') . '/includes',
      ),
    );    
     
    $info['FeedsHTTPFetcherExtended'] = array(
      'name' => 'HTTP Fetcher extended',
      'description' => 'HTTP fetcher tweaked for base44.core44.com',
      'handler' => array(
        'parent' => 'FeedsFetcher',
        'class' => 'FeedsHTTPFetcherExtended',
        'file' => 'FeedsHTTPFetcherExtended.inc',
        'path' => drupal_get_path('module', 'core44_feeds_pimp') . '/includes',
      ),
    ); 
    
    $info['FeedsHTTPFetcherSupport'] = array(
      'name' => 'HTTP Fetcher Support',
      'description' => 'HTTP fetcher tweaked for base44.core44.com',
      'handler' => array(
        'parent' => 'FeedsFetcher',
        'class' => 'FeedsHTTPFetcherSupport',
        'file' => 'FeedsHTTPFetcherSupport.inc',
        'path' => drupal_get_path('module', 'core44_feeds_pimp') . '/includes',
      ),
    );          
  
  if (module_exists('bean')) {  
      $info['FeedsBeanProcessor'] = array(
      'name' => 'Bean processor',
      'description' => 'Bean processor.',
      'help' => 'Create beans from parsed content. ',
      'handler' => array(
        'parent' => 'FeedsProcessor',
        'class' => 'FeedsBeanProcessor',
        'file' => 'FeedsBeanProcessor.inc',
        'path' => drupal_get_path('module', 'core44_feeds_pimp') . '/includes',
      ),
    );
  }
    
  return $info; 
}

/**
* Implementation of hook_enable.
*/
function core44_feeds_pimp_enable() {
  //clear the cache to display in Feeds as available plugin.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}