name = Brand Filter
description = A simple 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = brand-filter-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer
regions[hero]         	= Hero

; Stylesheets
stylesheets[all][] = assets/css/styles/layouts/brand-filter.layout.css
